name: Deploy to Aliyun

on:
  push:
    branches:
      - main  # 你想监听的分支

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Set up SSH
      uses: webfactory/ssh-agent@v0.8.0
      with:
        ssh-private-key: ${{ secrets.SSH_PRIVATE_KEY }}

    - name: Copy files to server
      run: |
        rsync -avz -e "ssh -p ${{ secrets.SERVER_PORT }}" ./ \
          ${{ secrets.SERVER_USER }}@${{ secrets.SERVER_HOST }}:/var/www/my_gitaction_test

    - name: Build and restart Docker on server
      run: |
        ssh -p ${{ secrets.SERVER_PORT }} ${{ secrets.SERVER_USER }}@${{ secrets.SERVER_HOST }} << 'EOF'
          cd /var/www/my_gitaction_test
          docker stop my_gitaction_test || true
          docker rm my_gitaction_test || true
          docker build -t my_gitaction_test .
          docker run -d --name my_gitaction_test -p 3000:3000 my_gitaction_test
        EOF
